### PR TITLE
Added an in-built Subscribe button

### LINKED ISSUE #4: Adding an in-built Subscribe button
## Current State : 
No such implementation yet.

## Expected Outcome : 
**_A Subscribe button to let users subscribe to FOSSASIA._**

### PR DESCRIPTION
**Pull request by prshntsingh**
fixes #4
Added an in-built Subscribe button.
@0x48piraj @gabru-md please review.

### CODE REVIEW

**Comment by 0x48piraj** [comment]
Please provide with a Screen Capture of the fix. 👍

**Comment by prshntsingh** [comment]
peek 2018-03-15 00-21

@0x48piraj please review

**Comment by 0x48piraj** [comment]
Working is great!
But, the UI is messed up.
Please create a "Subscribe" button as there are.
And then, after clicking the "Subscribe" button, direct users to a new page (with same background) and then put the input boxes.

**Comment by prshntsingh** [comment]
@0x48piraj Thank you.
Will do it.

**Pull request closed without merging**
