### PR TITLE
added subscribe button

### PR DESCRIPTION
**Pull request by mohitsharma23**

### CODE REVIEW

**Comment by Rishabh570** [comment]
@mohitsharma23 Please provide a screenshot of it.

**Comment by mohitsharma23** [comment]
screenshot 23
screenshot 25

It is same for both mozilla and chrome. I am having problems in redirecting to subscribe page. all i get is an empty page when clicking on submit. Any help there will be appreciated

**Comment by 0x48piraj** [comment]
And the Travis build is also failing.

**Comment by 0x48piraj** [comment]
By the way, if you are able to solve for firefox, great, otherwise, restore the codebase for firefox and apply only to chrome and open an issue for firefox and add your findings / logs

**Comment by mohitsharma23** [comment]
I will try to do it. @0x48piraj Can u help me guide through the Travis build, this is my first PR and i cant wrap my around travis. I know that it is failing because it is running the default Ruby check and mine is javascript! How can i pass that check? Thanx

**Comment by 0x48piraj** [comment]
Sorry for the late reply but, I haven't implemented / deployed the Travis CI on this repo.

**Comment by 0x48piraj** [comment]
Maybe @mariobehling can turn off the Travis CI on this repo for time being

**Pull request closed without merging**
